Browser("Advantage Shopping").Page("Advantage Shopping").Link("speakersImg").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").Link("speakersImg")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").Image("fetchImage?image_id=4600").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").Image("fetchImage?image id4600")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("save_to_cart").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("save to cart")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("check_out_btn").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("check out btn")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("registration_btnundefined").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("registration btnundefined")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("*Username").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("*Username")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("usernameRegisterPage").Set "per" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("usernameRegisterPage")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("emailRegisterPage").Set "per@per.com" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("emailRegisterPage")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("usernameRegisterPage").Set "perfe" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("usernameRegisterPage")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Password").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Password")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Password").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Password")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("passwordRegisterPage").SetSecure "5c7404ba1704a6bd2ca4bf624451" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("passwordRegisterPage")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Username").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Username")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("usernameRegisterPage").Set "ben" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("usernameRegisterPage")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("emailRegisterPage").Set "Ben@ben.com" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("emailRegisterPage")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("passwordRegisterPage").SetSecure "5c7404c7f615697519fe4803b9e2527becb2" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("passwordRegisterPage")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("confirm_passwordRegisterPage").SetSecure "5c7404c9a63425afff0fd7f954585786bdb2" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("confirm passwordRegisterPage")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("passwordRegisterPage").SetSecure "5c7404cc709ada62b7c0212f68b9ed5b3468b827" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("passwordRegisterPage")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("confirm_passwordRegisterPage").SetSecure "5c7404d22e661a77419427f1f9f15e8286334f8f" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("confirm passwordRegisterPage")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebCheckBox("i_agree").Set "ON" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebCheckBox("i agree")_;_script infofile_;_ZIP::ssf20.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebCheckBox("i_agree").Set "OFF" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebCheckBox("i agree")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebCheckBox("i_agree").Set "ON" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebCheckBox("i agree")_;_script infofile_;_ZIP::ssf22.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("register_btnundefined").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("register btnundefined")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("next_btn").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("next btn")_;_script infofile_;_ZIP::ssf24.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("ORDER PAYMENT 1. SHIPPING").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("ORDER PAYMENT 1. SHIPPING")_;_script infofile_;_ZIP::ssf25.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("ORDER PAYMENT 1. SHIPPING").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("ORDER PAYMENT 1. SHIPPING")_;_script infofile_;_ZIP::ssf26.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("SafePay username").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("SafePay username")_;_script infofile_;_ZIP::ssf27.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("SafePay username field").Drag 59,15 @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("SafePay username field")_;_script infofile_;_ZIP::ssf28.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("SafePay username field").Drop 57,16 @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("SafePay username field")_;_script infofile_;_ZIP::ssf29.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("safepay_username").Set "Benjamin" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("safepay username")_;_script infofile_;_ZIP::ssf30.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("safepay_password").SetSecure "5c740502223a9cde8606322a526e3889bee0" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("safepay password")_;_script infofile_;_ZIP::ssf31.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Back to shipping details").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Back to shipping details")_;_script infofile_;_ZIP::ssf32.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("*One number required").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("*One number required")_;_script infofile_;_ZIP::ssf33.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("safepay_password").SetSecure "5c740508496de3382261c9414c1ee5e7538d67ab" @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebEdit("safepay password")_;_script infofile_;_ZIP::ssf34.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("pay_now_btn_SAFEPAY").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebButton("pay now btn SAFEPAY")_;_script infofile_;_ZIP::ssf35.xml_;_
Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Thank you for buying with").Click @@ hightlight id_;_Browser("Advantage Shopping").Page("Advantage Shopping").WebElement("Thank you for buying with")_;_script infofile_;_ZIP::ssf36.xml_;_
